### ISSUE TITLE
Definition of default language for a property value

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#24]
In SpecIF you can define the property values in different languages or use a simple string if you do not need multiple languages.
To ensure the compatibility and the ability to convert data from simple string to multi-language representation and vice versa, an information about the used language in the string value is required. 

My first idea was to define a new JSON property "defaultLanguage" in the SpecIF heading data. But the problem is, that if you use SpecIF as API data you will not always get a complete SpecIF data structure, but just a Resource, Statement or Property alone.

So the proposal is to extend the "value" for a SpecIF property with a new JSON property "defaultLanguage":

     "defaultLanguage": {
                "description": "An IETF language tag such as 'en', 'en-US, 'fr' or 'de' - specifying the default language used for this value.",
                "type": "string"
              }

**Comment by odungern** [comment]
Yes, indeed, that's an issue. 
- Initially I thought that the default is the first language that is in the list. But perhaps some tools don't preserve the sequence. An explicit property is definitively better.
- Also I have thought that the default language is the browser language. This is, I think, a valid assumption, but perhaps there are use-cases which require an explicit denomination of the default.
- Final thought: I think the smallest item under versioning is the resource, statement or node. So we will not see a possibility to GET/PUT a single property in the API. (In fact, we had those calls in the ReqIF Server, but it has turned out that it was too fine-grained.) If we decide for the 'defaultLanguage', we can/should put it at the resource/statement level so that all it's properties are affected.

**Comment by odungern** [comment]
@oalt : Do you have a use-case where the browser-language is not adequate to determine the default language?

**Comment by odungern** [comment]
Approved in general in telco on 2020-01-29. @oalt points out that there is a need to declare the language in case only string values are provided.
It has been agreed that a 'language' property shall be added at resource or statement level. It applies to all properties which have no language definition. It is superseded by a property's language definition.

**Comment by odungern** [comment]
Implemented with schema v1.0.0,
