### ISSUE TITLE
Schema: Deal with quantitative units

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF#33]
In mechatronic systems (and others), a numeric value is often to be understood as measure of a unit, e.g. [m], [m/s] or [m^3/kg]. We haven't talked about this, yet. Where to specify a unit, dataType or propertyType?  Both is basically possible, but if ranges are defined with the dataTypes, units should be as well.
This question will get at us at the latest when we want to transform SysML parametric models.
Opinion, @oalt, @oeichmann and @S-Ruesch ?

**Comment by oeichmann** [comment]
In my opinion, DataTypes in UML and ValueTypes in SysmL are an important aspects and should be consiedered in the SpecIF schema. We will probably need to consider them already when dealing with SysML blocks, since blocks can have ValueTypes. It's also important when we think about model exchange with modeling tools with a stronger focus on mathematical expressions, e.g. Matlab Simulink. 
Therefore, we could think about adding SI units to 101_PrimitiveDatatypes.

**Comment by odungern** [comment]
After discussion we acknowledge that we have ideas, but no concrete use-case. Therefore we don't include it in the standard, for the time being: Rather add a feature than change it!

The current idea is to add the following optional attribute to the numeric dataTypes \"integer\" and \"double\":
```json
    "unit": {
      "description": "A unit for the numeric value given; preferrably an SI unit symbol such as 'm^3/kg' (Système international (d'unités)).",
      "$ref": "#/definitions/value"
    },
```
We postpone the definition until we actually deal with concrete use-cases such as the UML/SysML transformation.

**Comment by odungern** [comment]
Starting with schema v1.1, propertyClasses have an optional attribute;
```json
  "unit": {
    "description": "The unit of the numeric value given; preferrably an SI unit symbol such as 'm^3/kg' (Système international (d'unités)) or a currency symbol.",
    "type": "string"
  },
```
