### ISSUE TITLE
Make example model available again

### ISSUE THREAD

**Issue by koppor** [GfSE/SpecIF#44]
The [Tutorial 6: 'Very Simple Model (FMC)'](https://github.com/GfSE/SpecIF/blob/master/tutorials/06_Very-Simple-Model-FMC.md) shows following diagram:

![Very Simple Model (FMC)](https://github.com/GfSE/SpecIF/raw/cf5b54f5223799cdc55488381e7b997457e88243/tutorials/images/Very-Simple-Model-Relations.png)

When I open the SpecIF viewer at <https://specif.de/apps/view#view=doc;project=ACP-Very-Simple-Model-FMC;node=N-MEl-50fbfe8f0029b1a8016ea86245a9d83a>, I get following output:

![image](https://user-images.githubusercontent.com/1366654/99147710-5bf0a180-2683-11eb-9aa5-6181926b4224.png)

That means, no diagram is shown at all.

The root resource (https://specif.de/apps/view#view=doc;project=ACP-Very-Simple-Model-FMC;node=N-Diagram-aec0df7900010000017001eaf53e8876) shows a diagram:

![image](https://user-images.githubusercontent.com/1366654/99147718-6dd24480-2683-11eb-82f6-fe95953a6b77.png)

I really like that diagram as the syntax is 100% FMC Block Diagram (and not something custom as in tutorial 6)

**Comment by odungern** [comment]
Hi Oliver,
.. do you see the tabs directly under the project title?
- your first image shows the semantic net in the vicinity of FiCo-Application. Have a look at the tabs: Here the "Statements" resp. "Aussagen" tab is selected. This view is used for checking the model semantics wrt to completeness or consistency.
- your second image shows the tab "Document" resp. "Dokument", which is an outline of all model resources, so you can read the specification.
- try the "Filter" tab as well, 
- whereas the "Berichte" resp. "Reports" tab is not very useful for this simple case. 

However, I do not understand your last comment: What is "_something custom in tutorial 6_"?

**Comment by koppor** [comment]
Thank you for the quick response.

Minor comment: The link https://specif.de/apps/view#view=doc;project=ACP-Very-Simple-Model-FMC;node=N-MEl-50fbfe8f0029b1a8016ea86245a9d83a doesn't work any more. It should have been http://specif.de/apps-alpha/view.html#import=../examples/06_Very-Simple-Model-FMC.specifz. Should I open a new issue that links should be copyable (stable)?

Thank you for the clarification. I mis-interpreted the heading "FMC". I interpreted it as "FMC syntax and semantics is used in all diagrams belonging to this heading". I have to read it "The FMC diagram notation is shown at the top level, all other diagrams use another syntax and semantics".

I am new to this field; maybe the terms of the [C4 model](https://c4model.com/) could be used as heading? -- My issue is similar than "Business Process Model" versus "BPMN" or "System Structure and Behavior" versus "UML" in headings. With "BPMN" and "UML" expectations concerning the diagram syntax are triggered at my side.

Side note: Fun tweet on grapical representations: https://twitter.com/grady_booch/status/1258437678120333312

My comment regarding "something custom" is similar to my "System Structure and Behavior" vs. "UML". Very trivial. The heading "FMC" suggest that the diagrams on the page follow the FMC syntax. At least the first one. This is true.

The large one on the page is not FMC (and not UML). - It is my fault to look at the large things first on the page (heading and largest diagram).

Markings in yellow by me.

![grafik](https://user-images.githubusercontent.com/1366654/99182173-a03b7a80-2733-11eb-9bd2-5a5f72814d83.png)

**Comment by odungern** [comment]
Hi, Oliver,
.. thanks a lot ... it is important (however quite seldom) that readers feed back how they understand and what associations they have. I also like scrutinizing methods, concepts and models; some abstractions are useful and others are not ... and therefore I am trying to listen very closely to what you are saying ... I do not want to end up in the corner of academic bullshitting. To most of what you are saying I do not have an opinion or answer, yet ... but you have challenged my brain ;-). 

But let me note the following and explain my thinking ... and you may decide whether it is a useful approach for you or not:
- Thanks for the hint with the link; I will repair it (I hope I will find it ..). Yes of course, all links are meant to be copied to other media such as documents, backlog-items or e-mails. For the time being (there is no backend to the SpecIF Viewer/Editor, yet) any link must have a query string with "import=...", otherwise it has no content. The selection of the view and the element in the outline is optional.
- The first diagram is made by an analyst or engineer; the FMC Block Diagram notation has been chosen and others may have been used instead. I like FMC, others like other notations.
- The other diagram with nodes and directed edges (yes, indeed, this isn't a channel ..) does not follow any particular notation; it is a system-generated visualization of the semantic net in the vicinity of the selected model-element. It shows the effect of the modelling effort and allows to check the model from another perspective: It is very difficult to find contradictions when looking at a pile of hand-made diagrams, but is quite easy to see any problem when looking at the semantics of a given model-element ... which is the result of how it is being used by the ensemble of model-diagrams. For example, you see immediately, if a data-element is read, but never written.
- The C4 method is new to me. I will certainly have a closer look at it. As far as I can see from a first glance it is one approach among many others like SysML, Arcadia, Arc42, TOGAF/Archimate. None of them has achieved some sort of a "reference status", except TOGAF, perhaps. SpecIF is not a notation; it represents the content/meaning of _any_ modelling method/notation as a semantic net. In addition SpecIF may integrate different ones as long as they share some model-elements.

Do you agree with the line of thought? Is it useful for your application?

**Comment by odungern** [comment]
Wrt to the your hint on the link:
.. I have looked in the tutorial and did not find it. But now I think I know what you mean: A copied browser address line of the Viewer/Editor it is not useful as a link somewhere else. So far, it is maintained to allow using the browser back and forward buttons.
1. We could add the import information to the browser address line all the time, but then we must take care that this portion is ignored when the browser backward/forward is used. Perhaps this behavior is not easy to explain.
2. Perhaps it is better to offer a button that generates a link including the import information to copy it into the clipboard.

Good point ... thanks a lot for your proposal. We'll think about it. Which solution do you prefer? I will open an issue in the Viewer/Editor repo.

**Comment by koppor** [comment]
> Wrt to the your hint on the link:
> .. I have looked in the tutorial and did not find it.

https://github.com/GfSE/SpecIF/blob/master/tutorials/06_Very-Simple-Model-FMC.md

![grafik](https://user-images.githubusercontent.com/1366654/99196203-30f17500-278b-11eb-92b3-25595063df39.png)

This is <http://specif.de/apps-alpha/view.html#import=../examples/06_Very-Simple-Model-FMC.specifz>

Redirects to https://specif.de/apps-alpha/view.html#view=doc;project=ACP-Very-Simple-Model-FMC;node=N-Diagram-aec0df7900010000017001eaf53e8876

This link cannot be opened at another browser window.

> But now I think I know what you mean: A copied browser address line of the Viewer/Editor it is not useful as a link somewhere else. 

Yearh!

>     1. We could add the import information to the browser address line all the time, but then we must take care that this portion is ignored when the browser backward/forward is used. Perhaps this behavior is not easy to explain.

I made the experience, that "good looking URLs" is not a properity for many persons.

>     2. Perhaps it is better to offer a button that generates a link including the import information to copy it into the clipboard.

Please don't. 😇 This would be inconsistent to expectations. OK, spiegel.de also did that, but they crashed the system: http://blog.fefe.de/?ts=a1936030

> Good point ... thanks a lot for your proposal. We'll think about it. Which solution do you prefer? I will open an issue in the Viewer/Editor repo.

Thank you. Just a convenience feature.

**Comment by odungern** [comment]
Thanks for your opinion. In this case we cannot offer a satisfactory solution until there is a backend. 

If you think that the basic approach is valid and you find it interesting, we would appreciate your contribution. Fork it and submit a pull request with a solution which is good in your eyes.

**Comment by koppor** [comment]
> .. thanks a lot ...

The pleausre is on my side.

>     * The C4 method is new to me. I will certainly have a closer look at it. As far as I can see from a first glance it is one approach among many others like SysML, Arcadia, Arc42, TOGAF/Archimate.

C4 is both a method and a notation. When someone reaches out to me, I just say that it helps to structure the modeling of FMC block diagrams.

> Do you agree with the line of thought? 

Yes, I do.

> Is it useful for your application?

TBH, I just search for a good way to model a FMC diagram. I tried ARCWAY Cockpit (of which I liked the connection to project management), the Enterprise Architect plugin (https://github.com/oalt/fmc4se/issues/2) and Visio (https://github.com/f-m-c/FMCshapes). Still not satisfied. 

May I ask whether there is a list of the "Vielzahl von Werkzeugen, die ReqIF unterstützen" (gefunden unter https://specif.de/de/) so that I can evaluate more tools?

I came to SpecIF since I possibly just write the JSON manually by hand.

**Comment by odungern** [comment]
Then, you are one of the very few who know and apply the FMC. Welcome!

I have also used ARCWAY Cockpit for many years and sometime I still do. I have a server with 2 concurrent licenses ... and then I use the [ARCWAY-->SpecIF Exporter}(https://github.com/GfSE/ARCWAY-to-SpecIF-Exporter) to combine the result with others from other tools, e.g. BPMN from Camunda-Modeller and User-Stories from Excel. Works nicely.

- We have tried to use Visio and could use the TAM stencils which include the FMC Block Diagram. Some VisualBasic as in Philipp Mochines Thesis can do the job to export it to SpecIF. The code would need some refactoring and improvement, but it is no big deal.
- Then, my favorite is described in [Viewer-Issue 9](https://github.com/GfSE/SpecIF-Viewer/issues/9). This would be extremely powerful: Creating and Modifying FMC (and potential other diagram types) right from the [SpecIF Editor](https://specif.de/apps/edit).

**Comment by odungern** [comment]
> May I ask whether there is a list of the "Vielzahl von Werkzeugen, die ReqIF unterstützen" (gefunden unter https://specif.de/de/) so that I can evaluate more tools?

ReqIF has been made to exchange requirements in a neutral format. It is being used by quite many tools (IBM DOORS, PTC Integrity, :em ReqMan, just to mention a few), but as such they are just sending hierarchical lists of requirements ... with some relations between requirements. ReqIF can do more, it can also be used to transport semantic nets including SpecIF.

As already mentioned, ReqIF is just used for requirements exchange and so you should not expect to find a FMC modeller among ReqIF tools.

**Comment by odungern** [comment]
> I came to SpecIF since I possibly just write the JSON manually by hand.

So far, the [SpecIF Editor](https://specif.de/apps/edit) does not have a GUI to create and modify the types. So it is indeed needed to write (or copy from a template) a base specif-file with the types needed for the particular application. The content can be edited with a GUI ... except for graphical diagrams which need to be imported from modelling tools. By now, there are already some: ARCWAY Cockpit, Archi (with some manual work to include the diagram images), and BPMN-XML. Some work has been done to transform SysML to SpecIF, very encouraging ... but it is a whole lot of work. 

ARCWAY Cockpit, Archi and BPMN-XML transformations have less than 2000 LoC ... so writing new ones is in reach.
