### ISSUE TITLE
Use flat data storage in SpecIF

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#5]
## Issue
In SpecIF some data elements are stored as flat lists on the top level (dataTypes, resourceClasses, statementClasses, hierarchyClasses), but the property classes and node elements from the hierarchies are no flat structures. They are inside the JSON as tree structures.
## Proposal
Provide all data elements as flat structures and use references - similar to the _resourceReference_ in an node element to reference to the needed element. A storage in a simple list makes it easier to find an element (e.g. in a hierarchy), because you do not need to search a tree structure with a DFS or BFS algorithm. The second Advantage would be, that all data is represented in the same way in SpecIF: as an Array of objects on the top level.

**Comment by odungern** [comment]
- Pulling the property classes into an own list has an additional advantage of potential reuse by all resource classes, statement classes and hierarchy classes. As you point out, queries are easier to implement, indeed.
- Nodes can be in a flat list, as well. Each node would have to specify the parent to create a hierarchy. Displaying takes a little more effort, but searching is easier, as well.

Must still think a little about the consequences on operations such as inserting, moving and deleting a node.

**Comment by odungern** [comment]
.. driving the idea even further, we could combine all lists and distinguish the elements by a property 'category', e.g. 
`{   "id": "xyz123",
    "version": "0.10.6",
    "data": [{
        "id": "DT-String",
        "category": "dataType",
        "title": "String [512]",
        "description": "String with length 512",
        "type": "xs:string",
        "maxLength": 512,
        "revision": 1,
        "changedAt": "2016-05-26T08:59:00+02:00"
    },{
       ...
    },{
        "id": "PT-Title",
        "category": "propertyClass",
        "title": "dcterms:title",
        "dataType": "DT-String",
        "revision": 1,
        "changedAt": "2016-05-26T08:59:00+02:00"
    },{
       ...
    }
]}`

But I am not sure; there is a certain value in real JSON hierarchies. Also we may transport and store the data differently.

**Comment by odungern** [comment]
Having thought a little, I propose the following:
- We create a new list at the top level called "propertyClasses". All resourceClasses, statementClasses and hierarchyClasses may reference the elements in that list to specify their respective properties. This way, propertyClasses can be reused or not. The new approach would replace the current approach, where propertyClasses are defined privately ... in order to keep the schema as simple as possible.
- We do not flatten the list of nodes of the hierarchies. The current structure and a flat list can be easily transformed back and forth without any loss of information. So it is possible to flatten the list on import into a system or when storing it in a (document) database, if so desired.
- For the same reason, we do not combine the lists at the top level either.

@oalt : what do you think?

**Comment by oalt** [comment]
@odungern : Oskar, I aggree with your proposal to the properyClasses. And you are right with flatten the node lists using a transformation. I have done exacly this in my implementation of SpecIF using a MongoDB backend (will be published on GitHub soon). I have a list of nodes on the top level containing node elements and instead of having sub-elements of type node there is just a node reference using ID and revision. 
My proposal above, was also driven from the idea to avoid these transformation process when importing or exporting SpecIF data. I can live with your proposal, but for file-based SpecIF you will have still the problem when you search for a child-parent relation, you have to apply a tree-based seacrh instead of a list-based.

On the other side, wehen you want to read the JSON data of a SpecIF file manually, you can not see the tree structure of the node elements on the first side. But I think the modification (read/write) of SpecIF data by machines/tools is more important than the readability of the raw data for humans.

**Comment by odungern** [comment]
@oalt : ... in principle I agree with your last argument, that for a data structure the ease of processing is more important than readability by humans. However in this case I am tending to believe:
- Having some degree of human-readability simplifies fault diagnosis, if it comes down to the fundamentals.
- Also one might quickly create a test-case without recourse to any specific editor.
- Anyways we need some sort of import and export processing, because over the long run we need to support multiple versions of SpecIF. Looking at similar initiatives there is no reason to believe that the evolution would stop any time soon or that it will be always possible to develop the schema which is compatible with earlier versions. If we want to keep it as simple as possible, we need to get rid of schema options ... with the consequence of import processing.

**Comment by odungern** [comment]
@oalt : The schema has been modified so that the propertyClasses are at the top level and can be shared by all resourceClasses, statementClasses and hierarchyClasses. If you would like to review it, you are welcome: [SpecIF Schema v0.10.6 (draft)](https://github.com/GfSE/SpecIF/blob/SpecIF-Level-1/schema/specif.schema.json).
The constraint checker will be updated accordingly and a couple of test-cases will be provided within the next two weeks with all likelihood.

**Comment by odungern** [comment]
- Now, also the [constraint-checker](https://github.com/GfSE/SpecIF/blob/SpecIF-Level-1/check/specif.check.js) is updated to support v0.10.2 up until v0.10.6.
- 4 new test-cases have been added to [test-cases v0.10.2+](https://github.com/GfSE/SpecIF-Examples-and-Test-cases/tree/master/test-cases/v0.10.2%2B).

**Comment by odungern** [comment]
Now published at: 
- https://specif.de/v0.10.6/schema 
- https://specif.de/v0.10.6/check.js

... even though not yet released.

**Comment by odungern** [comment]
Now published:
- https://specif.de/v0.11.6/schema (corresponding to v0.10.6, still in draft status)

**Comment by odungern** [comment]
Now, both SpecIF-levels have been updated to support propertyClasses at the top level, which can be shared between all resourceClasses, statementClasses and hierachyClasses. Both the schemata and the constraint-checks are now available (CORS-enabled):
- https://specif.de/v0.10.6/schema
- https://specif.de/v0.10.6/check.js
- https://specif.de/v0.11.6/schema
- https://specif.de/v0.11.6/check.js

Anyone who wants to test is happily welcome!

(Remember: The difference between the v0.10.x series and the v0.11.x series is that the latter supports multiple revisions of the same element and also multiple languages for property values of type text. The v0.11.x schema supports all data-sets adhering to the v0.10.x schema).

**Comment by odungern** [comment]
It has been decided in a meeting 
- to provide a flat list of property classes at the top level, which can be shared by all resourceClasses, statementClasses and hierarchyClasses. 
- not to provide a possibility to represent hierarchy nodes in a flat list. Reasons are (1) to keep the schema simple and (2) the ability to transform the lists easily with information loss.
