### ISSUE TITLE
Make a dcterms:title mandatory for each Resource

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#57]
Some vocabulary elements have currently no title defined:

* Comment
* Paragraph - The title can be used as marginal note

I would suggest to make the dcterms:title property mandatory for each Resource, so a tool can always use it as tree node name in a hierarchy view.

If no title is available in the source tool, a SpecIF adapter shall set a dummy title or an empty string.

**Comment by oalt** [comment]
Also make description mandatory when native title and description is removed?

**Comment by odungern** [comment]
Agreed for the title, but not description. The resources and statements don't have a native title attribute any more starting with schema v1.1. But they must have a property list with at least one element. The constraintChecker will take care to check whether there is always a property with "title": "dcterms:title".

**Comment by odungern** [comment]
Open again, until the constraint checker has implemented it.

**Comment by odungern** [comment]
The constraint checker now assures that 
- a resource must have at least one property (there are no more native title and description attributes any more to avoid redundancy), so that there cannot be a resource without payload.
- There are examples of resources without title, for example simple paragraphs in a chapter. Therefore it is only required, that there is at least one property, but it mustn't be a title.
- in case of inheritance, the base resource must have at least one property, the children may not define any additional.
- a statement may exist without any property, because the statementClass' title can be used - statements of the same type should have the same title, anyways. But it is possible to give an individual title to every statement by use of a property typed by title 'dcterms:title'

**Comment by odungern** [comment]
So the original request is not yet agreed and enforced. To my opinion we should not exclude the existence of resources without title. We could think of a warning, if a resource has neither title nor description property.

**Comment by odungern** [comment]
@oalt : Do you agree with the proposal, which is implemented in both schema and constraint checker for v1.1. Please close the issue, if you consent, in particular with the issue that resources without title property are allowed (they must have at least one property ..).

**Comment by oalt** [comment]
After discussion we support a title as property in the resources but have also a title in the node element for quick loading of the hierarchy tree.
