### ISSUE TITLE
Rename the model integration resource type titles?

### ISSUE THREAD

**Issue by oalt** [GfSE/SpecIF#59]
After some discussions about the semantic model integration using the fundamental modeling elements 'Actor', 'State' and 'Event' some people are confused about mapping for example an object to a state etc.

Should we think about a more generic naming of the model integration resource classes? 

For example:

* ActiveElement instead of Actor
* PassiveElement  instead of State

**Comment by odungern** [comment]
... valid thought. I think however that the basic question does not depend on the naming. A UML-object is both active (has methods) and is passive (has attributes). A typical object however has methods working on local attributes ... and so an object is better characterised as a holder of information (=passive aspect=state) than a modifier of information (=active aspect). Have a look at the dimmer example: In spite of it's functions, the main dimmer is modelled as a state, because it shows best it's role as memory of desired illumination.
Namen sind Schall und Rauch - am Ende spielt es keine Rolle.
Let's talk, O.

**Comment by odungern** [comment]
@oalt : unless there is a strong endorsement from your side, I propose to turn down the idea.

**Comment by oalt** [comment]
As discussed: We do not change the model integration terms for the first SpecIF release.
